import './globals.css';
import { Roboto } from 'next/font/google';
import PageHeader from '@/components/PageHeader/PageHeader';
import ContentWrapper from '@/components/ContentWrapper/ContentWrapper';
import PageFooter from '@/components/PageFooter/PageFooter';

const roboto = Roboto({ 
  subsets: ['cyrillic'],
  display: 'swap',
  weight: ['400', '700']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        
        <PageHeader />

        <ContentWrapper>
          {children}
        </ContentWrapper>

        <PageFooter/>
      </body>
    </html>
  );
}
